import { useState, useEffect } from 'react';
import { supabase } from '../../lib/supabaseClient';
import { FileText, Download, BarChart2, TrendingUp, Users, CreditCard, Receipt, DollarSign, Calendar, RefreshCw } from 'lucide-react';
import { exportToCSV, exportToPDF } from '../../utils/export';

interface ReportCard {
  id: string;
  name: string;
  description: string;
  icon: React.ElementType;
  color: string;
  lastGenerated?: string;
}

const REPORTS: ReportCard[] = [
  { id: 'daily_cash', name: 'Daily Cash Report', description: 'Summary of all cash transactions for the day', icon: DollarSign, color: '#10b981', lastGenerated: 'Dec 10, 2024 6:00 PM' },
  { id: 'weekly_sales', name: 'Weekly Sales Report', description: 'Sales performance and order summary for the week', icon: TrendingUp, color: '#6366f1', lastGenerated: 'Dec 8, 2024 5:00 PM' },
  { id: 'monthly_pl', name: 'Monthly P&L Statement', description: 'Profit and loss overview for the month', icon: BarChart2, color: 'var(--accent)', lastGenerated: 'Nov 30, 2024 11:59 PM' },
  { id: 'quarterly', name: 'Quarterly Financial Summary', description: 'Comprehensive financial review for the quarter', icon: Calendar, color: '#f59e0b', lastGenerated: 'Sep 30, 2024 11:59 PM' },
  { id: 'annual', name: 'Annual Report', description: 'Full-year financial report and analysis', icon: FileText, color: '#3b82f6', lastGenerated: 'Dec 31, 2023 11:59 PM' },
  { id: 'vat', name: 'VAT Report (GRA Format)', description: 'VAT return in GRA-compliant format', icon: Receipt, color: '#8b5cf6', lastGenerated: 'Nov 30, 2024 10:00 AM' },
  { id: 'payroll', name: 'Payroll Summary', description: 'Department payroll totals and processing status', icon: Users, color: '#06b6d4', lastGenerated: 'Nov 28, 2024 3:00 PM' },
  { id: 'credit', name: 'Customer Credit Report', description: 'Outstanding credit balances and collection status', icon: CreditCard, color: '#ef4444', lastGenerated: 'Dec 9, 2024 2:00 PM' },
  { id: 'outstanding_inv', name: 'Outstanding Invoices', description: 'All unpaid invoices with aging breakdown', icon: FileText, color: '#f97316', lastGenerated: 'Dec 10, 2024 9:00 AM' },
  { id: 'payment_methods', name: 'Payment Methods Analysis', description: 'Breakdown of payments by method and network', icon: BarChart2, color: '#10b981', lastGenerated: 'Dec 8, 2024 4:00 PM' },
  { id: 'expense', name: 'Expense Report', description: 'All approved and pending expense submissions', icon: Receipt, color: '#6366f1', lastGenerated: 'Dec 7, 2024 5:00 PM' },
  { id: 'bank_recon', name: 'Bank Reconciliation', description: 'Bank statement vs. internal records reconciliation', icon: RefreshCw, color: '#f59e0b', lastGenerated: 'Dec 5, 2024 6:00 PM' },
];

interface ReportHistoryEntry {
  date: string;
  type: string;
  period: string;
  generatedBy: string;
}

interface Props {
  addNotification?: (msg: string) => void;
  currentUser?: { fullName: string; department: string } | null;
}

export default function FinanceReportsView({ addNotification, currentUser }: Props) {
  const [generating, setGenerating] = useState<string | null>(null);
  const [showPeriodModal, setShowPeriodModal] = useState<ReportCard | null>(null);
  const [selectedPeriod, setSelectedPeriod] = useState('This Month');
  const [reportHistory, setReportHistory] = useState<ReportHistoryEntry[]>([]);
  const [historyLoading, setHistoryLoading] = useState(true);

  useEffect(() => {
    const load = async () => {
      setHistoryLoading(true);
      try {
        const { data } = await supabase
          .from('finance_report_history')
          .select('*')
          .order('created_at', { ascending: false })
          .limit(50);
        setReportHistory((data ?? []) as ReportHistoryEntry[]);
      } catch {
        setReportHistory([]);
      }
      setHistoryLoading(false);
    };
    load();
  }, []);

  function generateReport(report: ReportCard) {
    setShowPeriodModal(null);
    setGenerating(report.id);
    setTimeout(() => {
      exportToPDF(
        `${report.name} — ${selectedPeriod}`,
        [{ Report: report.name, Period: selectedPeriod, 'Generated By': currentUser?.fullName || 'Finance', Date: new Date().toLocaleDateString() }],
        ['Report', 'Period', 'Generated By', 'Date']
      );
      setGenerating(null);
      addNotification?.(`${report.name} generated for ${selectedPeriod}`);
    }, 800);
  }

  return (
    <div className="p-4 md:p-6 space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-[var(--text-primary)]">Financial Reports</h1>
        <p className="text-sm text-[var(--text-secondary)]">Generate and download financial reports</p>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-4">
        {REPORTS.map(report => {
          const Icon = report.icon;
          return (
            <div key={report.id} className="bg-[var(--bg-card)] border border-[var(--border)] rounded-2xl p-5 flex flex-col gap-3 hover:border-[var(--accent)] transition-colors group">
              <div className="flex items-start gap-3">
                <div className="w-10 h-10 rounded-xl flex items-center justify-center flex-shrink-0" style={{ background: `${report.color}20` }}>
                  <Icon size={18} style={{ color: report.color }} />
                </div>
                <div className="flex-1">
                  <h3 className="text-sm font-semibold text-[var(--text-primary)]">{report.name}</h3>
                  <p className="text-xs text-[var(--text-muted)] mt-0.5">{report.description}</p>
                </div>
              </div>
              {report.lastGenerated && (
                <p className="text-xs text-[var(--text-muted)]">Last: {report.lastGenerated}</p>
              )}
              <button
                onClick={() => setShowPeriodModal(report)}
                disabled={generating === report.id}
                className={`flex items-center justify-center gap-1.5 w-full py-2 rounded-xl text-white text-sm font-medium transition-opacity ${generating === report.id ? 'opacity-60' : 'hover:opacity-90'}`}
                style={{ background: report.color }}
              >
                {generating === report.id ? (
                  <><RefreshCw size={14} className="animate-spin" /> Generating...</>
                ) : (
                  <><Download size={14} /> Generate Report</>
                )}
              </button>
            </div>
          );
        })}
      </div>

      <div className="bg-[var(--bg-card)] border border-[var(--border)] rounded-2xl p-5">
        <div className="flex items-center justify-between mb-4">
          <h3 className="font-semibold text-[var(--text-primary)]">Report History</h3>
          <button onClick={() => exportToCSV(reportHistory, ['date', 'type', 'period', 'generatedBy'], 'report_history')} className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-[var(--border)] text-xs text-[var(--text-secondary)] hover:bg-[var(--bg-input)]"><Download size={12} /> Export</button>
        </div>
        {historyLoading ? (
          <div>{[0,1,2,3,4].map(i => <div key={i} className="animate-pulse h-10 bg-slate-200 dark:bg-slate-700 rounded mb-2" />)}</div>
        ) : reportHistory.length === 0 ? (
          <div className="flex flex-col items-center py-8 text-[var(--text-muted)]">
            <FileText size={28} className="opacity-30 mb-2" />
            <p className="text-sm">No report history yet</p>
          </div>
        ) : (
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead><tr className="border-b border-[var(--border)]">{['Date', 'Report Type', 'Period', 'Generated By', 'Download'].map(h => <th key={h} className="px-4 py-3 text-left text-xs font-medium text-[var(--text-muted)] uppercase tracking-wide whitespace-nowrap">{h}</th>)}</tr></thead>
            <tbody className="divide-y divide-[var(--border)]">
              {reportHistory.map((h, i) => (
                <tr key={i} className="hover:bg-[var(--bg-input)]">
                  <td className="px-4 py-3 text-[var(--text-muted)] whitespace-nowrap">{h.date}</td>
                  <td className="px-4 py-3 font-medium text-[var(--text-primary)]">{h.type}</td>
                  <td className="px-4 py-3 text-[var(--text-secondary)]">{h.period}</td>
                  <td className="px-4 py-3 text-[var(--text-secondary)] whitespace-nowrap">{h.generatedBy}</td>
                  <td className="px-4 py-3">
                    <button onClick={() => window.print()} className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-[var(--border)] text-xs text-[var(--text-secondary)] hover:bg-[var(--bg-input)]"><Download size={12} /> Download PDF</button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        )}
      </div>

      {showPeriodModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4" onClick={() => setShowPeriodModal(null)}>
          <div className="absolute inset-0 bg-black/40 backdrop-blur-sm" />
          <div className="relative bg-[var(--bg-card)] border border-[var(--border)] rounded-2xl p-6 w-full max-w-sm shadow-2xl" onClick={e => e.stopPropagation()}>
            <h3 className="text-base font-semibold text-[var(--text-primary)] mb-1">{showPeriodModal.name}</h3>
            <p className="text-xs text-[var(--text-muted)] mb-5">{showPeriodModal.description}</p>
            <div>
              <label className="text-xs font-medium text-[var(--text-secondary)] mb-1 block">Select Period</label>
              <select value={selectedPeriod} onChange={e => setSelectedPeriod(e.target.value)} className="w-full px-3 py-2.5 rounded-xl bg-[var(--bg-input)] border border-[var(--border)] text-sm focus:outline-none focus:border-[var(--accent)]">
                {['Today', 'This Week', 'This Month', 'Last Month', 'This Quarter', 'Last Quarter', 'This Year', 'Last Year'].map(p => <option key={p}>{p}</option>)}
              </select>
            </div>
            <div className="flex items-center gap-3 justify-end mt-5">
              <button onClick={() => setShowPeriodModal(null)} className="px-4 py-2 rounded-xl border border-[var(--border)] text-sm font-medium text-[var(--text-secondary)]">Cancel</button>
              <button onClick={() => generateReport(showPeriodModal)} className="flex items-center gap-1.5 px-4 py-2 rounded-xl text-white text-sm font-medium" style={{ background: showPeriodModal.color }}><Download size={14} /> Generate & Download</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
