// rebma-mobile/screens/finance/FinReportsScreen.tsx
// Ports: rebma-web/src/views/finance/ReportsView.tsx — one generic
// component, one `generateReport(report)` dispatcher on web (a long
// if/else chain, not 12 separate files/components — mirrored here as one
// `runReport()` dispatcher too). Web hands every report's result straight
// to `exportToPDF` and never renders it on screen; this screen renders
// every report's real result in a Sheet (Gap-Closure Backlog, Item 2,
// D107) AND offers a real PDF/CSV export via the shared ExportSheet
// (Item 1) — closing the "only ever inside a generated PDF" gap for good.
//
// Of the 12 report types, only 8 have real Supabase-backed logic on web
// itself — `quarterly`, `annual`, `vat`, `bank_recon` fall into web's own
// generic `else` branch and produce nothing but a single placeholder row
// (`{ Report, Period, Generated By, Date }`). Ported as the same honest
// placeholder, not invented (D106) — same confirmed-real-vs-confirmed-fake
// discipline as every other phase in this rollout.
//
// Every report run still writes the same finance_report_history row
// (date/type/period/generated_by/created_at) web's own unconditional
// insert does — including for the 4 mock types (ReportsView.tsx:256-270).
import { useCallback, useState } from 'react';
import { View, Text, Alert } from 'react-native';
import {
  DollarSign, TrendingUp, CreditCard, ShoppingCart, ChartPie, Calendar,
  Receipt, Users, TriangleAlert, Wallet, FileMinus, Landmark, Download,
} from 'lucide-react-native';
import { supabase } from '../../lib/supabaseClient';
import { useAuthStore } from '../../store/authStore';
import { useTheme } from '../../theme/ThemeProvider';
import Screen from '../../components/ui/Screen';
import Card from '../../components/ui/Card';
import DataList, { type DataColumn } from '../../components/ui/DataList';
import Badge, { statusTone } from '../../components/ui/Badge';
import Sheet, { SheetSection } from '../../components/ui/Sheet';
import Button from '../../components/ui/Button';
import SearchablePicker from '../../components/ui/SearchablePicker';
import ExportSheet from '../../components/shared/ExportSheet';
import type { ExportColumn } from '../../lib/exportEngine';

const PERIODS = ['Today', 'This Week', 'This Month', 'Last Month', 'This Quarter', 'This Year'];

const REPORTS = [
  { id: 'daily_cash', name: 'Daily Cash Report', description: 'Cash payments received', icon: DollarSign, color: '#10b981' },
  { id: 'weekly_sales', name: 'Weekly Sales Report', description: 'Orders for the selected period', icon: ShoppingCart, color: '#3b82f6' },
  { id: 'monthly_pl', name: 'Monthly P&L Statement', description: 'Revenue vs approved expenses', icon: TrendingUp, color: '#22c55e' },
  { id: 'quarterly', name: 'Quarterly Financial Summary', description: 'No real data on web either — placeholder', icon: ChartPie, color: '#8b5cf6' },
  { id: 'annual', name: 'Annual Report', description: 'No real data on web either — placeholder', icon: Calendar, color: '#06b6d4' },
  { id: 'vat', name: 'VAT Report (GRA Format)', description: 'No real data on web either — placeholder', icon: Receipt, color: '#f59e0b' },
  { id: 'payroll', name: 'Payroll Summary', description: 'Active staff roster (no pay figures — matches web)', icon: Users, color: '#14b8a6' },
  { id: 'credit', name: 'Customer Credit Report', description: 'Outstanding credit balances', icon: CreditCard, color: '#ef4444' },
  { id: 'outstanding_inv', name: 'Outstanding Invoices', description: 'Unpaid/in-progress orders', icon: TriangleAlert, color: '#f97316' },
  { id: 'payment_methods', name: 'Payment Methods Analysis', description: 'Collections grouped by payment mode', icon: Wallet, color: '#0ea5e9' },
  { id: 'expense', name: 'Expense Report', description: 'General purchases (all statuses — matches web)', icon: FileMinus, color: '#dc2626' },
  { id: 'bank_recon', name: 'Bank Reconciliation', description: 'No real data on web either — placeholder', icon: Landmark, color: '#64748b' },
];

function periodStartDate(period: string): string | null {
  const now = new Date();
  if (period === 'Today') { const d = new Date(now); d.setHours(0, 0, 0, 0); return d.toISOString(); }
  if (period === 'This Week') { const d = new Date(now); d.setDate(now.getDate() - now.getDay()); d.setHours(0, 0, 0, 0); return d.toISOString(); }
  if (period === 'This Month') return new Date(now.getFullYear(), now.getMonth(), 1).toISOString();
  if (period === 'Last Month') return new Date(now.getFullYear(), now.getMonth() - 1, 1).toISOString();
  if (period === 'This Quarter') return new Date(now.getFullYear(), Math.floor(now.getMonth() / 3) * 3, 1).toISOString();
  if (period === 'This Year') return new Date(now.getFullYear(), 0, 1).toISOString();
  return null;
}

export default function FinReportsScreen() {
  const t = useTheme();
  const { profile } = useAuthStore();
  const [period, setPeriod] = useState('This Month');
  const [running, setRunning] = useState<string | null>(null);
  const [resultReport, setResultReport] = useState<string | null>(null);
  const [resultRows, setResultRows] = useState<any[]>([]);
  const [resultColumns, setResultColumns] = useState<DataColumn<any>[]>([]);
  const [exportColumns, setExportColumns] = useState<ExportColumn[]>([]);
  const [exportOpen, setExportOpen] = useState(false);

  const logHistory = async (reportName: string) => {
    try {
      await supabase.from('finance_report_history').insert([{
        date: new Date().toISOString().slice(0, 10), type: reportName, period, generated_by: profile?.fullName || 'Finance', created_at: new Date().toISOString(),
      }]);
    } catch {}
  };

  const runDailyCash = useCallback(async () => {
    const gte = periodStartDate(period);
    let query = supabase.from('finance_payments').select('id, client_name, amount, payment_mode, payment_type, recorded_by, created_at').eq('payment_mode', 'Cash');
    if (gte) query = query.gte('created_at', gte);
    const { data } = await query;
    setResultColumns([
      { key: 'client_name', label: 'Client', primary: true, render: (p) => p.client_name || '—' },
      { key: 'amount', label: 'Amount', status: true, render: (p) => <Text style={{ fontFamily: t.font.bold, fontSize: t.type.body12.size, color: t.colors.textPrimary }}>GHS {Number(p.amount || 0).toLocaleString()}</Text> },
      { key: 'payment_type', label: 'Type', render: (p) => p.payment_type || '—' },
      { key: 'recorded_by', label: 'Recorded By', render: (p) => p.recorded_by || '—' },
    ]);
    setExportColumns([
      { key: 'id', label: 'Receipt ID' },
      { key: 'client_name', label: 'Client Name', render: (p) => p.client_name || '' },
      { key: 'amount', label: 'Amount (GHS)', render: (p) => Number(p.amount || 0).toLocaleString() },
      { key: 'payment_mode', label: 'Payment Mode' },
      { key: 'payment_type', label: 'Payment Type', render: (p) => p.payment_type || '' },
      { key: 'recorded_by', label: 'Recorded By', render: (p) => p.recorded_by || '' },
      { key: 'created_at', label: 'Date', render: (p) => new Date(p.created_at).toLocaleDateString() },
    ]);
    setResultRows(data || []);
  }, [period, t]);

  // Verbatim from ReportsView.tsx:129-142 — despite the "weekly" name,
  // web uses whatever period is selected, not a hardcoded 7-day window.
  const runWeeklySales = useCallback(async () => {
    const gte = periodStartDate(period);
    let query = supabase.from('orders').select('id, client_name, product_name, quantity, total_amount, payment_mode, status, created_at');
    if (gte) query = query.gte('created_at', gte);
    const { data } = await query;
    setResultColumns([
      { key: 'client_name', label: 'Client', primary: true, render: (o) => o.client_name || '—' },
      { key: 'status', label: 'Status', status: true, render: (o) => <Badge tone={statusTone(o.status)} label={String(o.status).replace(/_/g, ' ')} /> },
      { key: 'product_name', label: 'Product', render: (o) => o.product_name || '—' },
      { key: 'total_amount', label: 'Amount', render: (o) => `GHS ${Number(o.total_amount || 0).toLocaleString()}` },
    ]);
    setExportColumns([
      { key: 'id', label: 'Order ID' },
      { key: 'client_name', label: 'Client Name', render: (o) => o.client_name || '' },
      { key: 'product_name', label: 'Product Name', render: (o) => o.product_name || '—' },
      { key: 'quantity', label: 'Quantity', render: (o) => String(o.quantity || 1) },
      { key: 'total_amount', label: 'Amount (GHS)', render: (o) => Number(o.total_amount || 0).toLocaleString() },
      { key: 'payment_mode', label: 'Payment Mode' },
      { key: 'status', label: 'Status' },
      { key: 'created_at', label: 'Date', render: (o) => new Date(o.created_at).toLocaleDateString() },
    ]);
    setResultRows(data || []);
  }, [period]);

  const runMonthlyPL = useCallback(async () => {
    const gte = periodStartDate(period);
    let pQuery = supabase.from('finance_payments').select('amount, created_at');
    let eQuery = supabase.from('general_purchases').select('cost, created_at').eq('status', 'APPROVED');
    if (gte) { pQuery = pQuery.gte('created_at', gte); eQuery = eQuery.gte('created_at', gte); }
    const [{ data: pData }, { data: eData }] = await Promise.all([pQuery, eQuery]);
    const rev = (pData || []).reduce((s: number, p: any) => s + Number(p.amount || 0), 0);
    const exp = (eData || []).reduce((s: number, e: any) => s + Number(e.cost || 0), 0);
    const net = rev - exp;
    const cols: DataColumn<any>[] = [
      { key: 'metric', label: 'Metric', primary: true },
      { key: 'amount', label: 'Amount', status: true, render: (r) => <Text style={{ fontFamily: t.font.bold, fontSize: t.type.body12.size, color: r.amount < 0 ? t.colors.status.danger.text : t.colors.textPrimary }}>GHS {r.amount.toLocaleString()}</Text> },
      { key: 'description', label: 'Description' },
    ];
    setResultColumns(cols);
    setExportColumns([
      { key: 'metric', label: 'Metric' },
      { key: 'amount', label: 'Amount (GHS)', render: (r) => String(r.amount.toLocaleString()) },
      { key: 'description', label: 'Description' },
    ]);
    setResultRows([
      { metric: 'Total Revenue (Collections)', amount: rev, description: 'Revenue collected from payments' },
      { metric: 'Total Approved Expenses', amount: exp, description: 'Operations & general purchases approved' },
      { metric: 'Net Operating Income', amount: net, description: 'Net profit/loss before tax' },
    ]);
  }, [period, t]);

  // Verbatim from ReportsView.tsx:169-179 — a staff roster, no pay
  // figures at all, matching web's real (not the card's described)
  // behavior. No date filter, matching web.
  const runPayroll = useCallback(async () => {
    const { data } = await supabase.from('profiles_directory').select('*').eq('status', 'ACTIVE');
    setResultColumns([
      { key: 'full_name', label: 'Name', primary: true, render: (s) => s.full_name || '—' },
      { key: 'role', label: 'Role', status: true, render: (s) => <Badge tone="muted" label={s.role || 'Staff'} /> },
      { key: 'department', label: 'Department', render: (s) => s.department || '—' },
      { key: 'phone', label: 'Phone', render: (s) => s.phone || '—' },
    ]);
    setExportColumns([
      { key: 'id', label: 'Staff ID', render: (s) => String(s.id || '').slice(0, 8).toUpperCase() },
      { key: 'full_name', label: 'Full Name', render: (s) => s.full_name || '—' },
      { key: 'role', label: 'Role', render: (s) => s.role || 'Staff' },
      { key: 'department', label: 'Department', render: (s) => s.department || '—' },
      { key: 'phone', label: 'Phone', render: (s) => s.phone || '—' },
      { key: 'status', label: 'Status' },
    ]);
    setResultRows(data || []);
  }, []);

  const runCredit = useCallback(async () => {
    const { data } = await supabase.from('orders').select('id, client_name, total_amount, status, created_at').eq('payment_mode', 'CREDIT');
    setResultColumns([
      { key: 'client_name', label: 'Client', primary: true },
      { key: 'status', label: 'Status', status: true, render: (o) => <Badge tone={statusTone(o.status)} label={o.status.replace(/_/g, ' ')} /> },
      { key: 'total_amount', label: 'Amount', render: (o) => `GHS ${Number(o.total_amount || 0).toLocaleString()}` },
      { key: 'created_at', label: 'Date', render: (o) => new Date(o.created_at).toLocaleDateString() },
    ]);
    setExportColumns([
      { key: 'id', label: 'Order ID' },
      { key: 'client_name', label: 'Client Name' },
      { key: 'total_amount', label: 'Total Amount (GHS)', render: (o) => Number(o.total_amount || 0).toLocaleString() },
      { key: 'status', label: 'Status' },
      { key: 'created_at', label: 'Date Placed', render: (o) => new Date(o.created_at).toLocaleDateString() },
    ]);
    setResultRows(data || []);
  }, []);

  // Verbatim from ReportsView.tsx:196-207 — no aging-bucket computation
  // despite the card description implying one; web doesn't compute it
  // either. No date filter, matching web.
  const runOutstandingInvoices = useCallback(async () => {
    const { data } = await supabase.from('orders').select('id, ticket_number, client_name, product_name, total_amount, payment_mode, status, created_at').in('status', ['PENDING_FINANCE', 'PENDING_MANAGEMENT', 'PROCESSING', 'OUT_FOR_DELIVERY']);
    setResultColumns([
      { key: 'client_name', label: 'Client', primary: true },
      { key: 'status', label: 'Status', status: true, render: (o) => <Badge tone={statusTone(o.status)} label={String(o.status).replace(/_/g, ' ')} /> },
      { key: 'total_amount', label: 'Amount', render: (o) => `GHS ${Number(o.total_amount || 0).toLocaleString()}` },
      { key: 'created_at', label: 'Date', render: (o) => new Date(o.created_at).toLocaleDateString() },
    ]);
    setExportColumns([
      { key: 'invoiceId', label: 'Invoice ID', render: (o) => o.ticket_number || o.id },
      { key: 'client_name', label: 'Client Name' },
      { key: 'product_name', label: 'Product Name', render: (o) => o.product_name || '—' },
      { key: 'total_amount', label: 'Amount (GHS)', render: (o) => Number(o.total_amount || 0).toLocaleString() },
      { key: 'payment_mode', label: 'Payment Mode' },
      { key: 'status', label: 'Invoice Status' },
      { key: 'created_at', label: 'Date Issued', render: (o) => new Date(o.created_at).toLocaleDateString() },
    ]);
    setResultRows(data || []);
  }, []);

  // Verbatim from ReportsView.tsx:211-224 — real grouping/summation, no
  // date filter, matching web.
  const runPaymentMethods = useCallback(async () => {
    const { data } = await supabase.from('finance_payments').select('payment_mode, amount');
    const groups: Record<string, { count: number; total: number }> = {};
    for (const p of data || []) {
      const mode = p.payment_mode || 'Unknown';
      if (!groups[mode]) groups[mode] = { count: 0, total: 0 };
      groups[mode].count += 1;
      groups[mode].total += Number(p.amount || 0);
    }
    const rows = Object.entries(groups).map(([mode, s]) => ({ payment_method: mode, transaction_count: s.count, total_collected: s.total }));
    setResultColumns([
      { key: 'payment_method', label: 'Method', primary: true },
      { key: 'total_collected', label: 'Total', status: true, render: (r) => <Text style={{ fontFamily: t.font.bold, fontSize: t.type.body12.size, color: t.colors.textPrimary }}>GHS {r.total_collected.toLocaleString()}</Text> },
      { key: 'transaction_count', label: 'Count' },
    ]);
    setExportColumns([
      { key: 'payment_method', label: 'Payment Method' },
      { key: 'transaction_count', label: 'Transaction Count', render: (r) => String(r.transaction_count) },
      { key: 'total_collected', label: 'Total Collected (GHS)', render: (r) => r.total_collected.toLocaleString() },
    ]);
    setResultRows(rows);
  }, [t]);

  // Verbatim from ReportsView.tsx:229-242 — no status filter, matching
  // web's real (not the card's described) behavior.
  const runExpense = useCallback(async () => {
    const gte = periodStartDate(period);
    let query = supabase.from('general_purchases').select('id, item_name, category, cost, status, department, date_received, created_at');
    if (gte) query = query.gte('created_at', gte);
    const { data } = await query;
    setResultColumns([
      { key: 'item_name', label: 'Item', primary: true, render: (e) => e.item_name || '—' },
      { key: 'status', label: 'Status', status: true, render: (e) => <Badge tone={statusTone(e.status)} label={e.status || 'PENDING'} /> },
      { key: 'category', label: 'Category', render: (e) => e.category || 'General' },
      { key: 'cost', label: 'Cost', render: (e) => `GHS ${Number(e.cost || 0).toLocaleString()}` },
    ]);
    setExportColumns([
      { key: 'id', label: 'Expense ID' },
      { key: 'item_name', label: 'Item Name', render: (e) => e.item_name || '' },
      { key: 'category', label: 'Category', render: (e) => e.category || 'General' },
      { key: 'cost', label: 'Cost (GHS)', render: (e) => Number(e.cost || 0).toLocaleString() },
      { key: 'status', label: 'Status' },
      { key: 'department', label: 'Department', render: (e) => e.department || '—' },
      { key: 'date_received', label: 'Date Received', render: (e) => e.date_received || '—' },
    ]);
    setResultRows(data || []);
  }, [period]);

  // Confirmed mock on web itself (ReportsView.tsx:244-248) — a single
  // placeholder row, no Supabase call. Ported as the same honest
  // placeholder, not invented (D106).
  const runMockPlaceholder = useCallback((reportName: string) => {
    const row = { Report: reportName, Period: period, 'Generated By': profile?.fullName || 'Finance', Date: new Date().toLocaleDateString() };
    setResultColumns([
      { key: 'Report', label: 'Report', primary: true },
      { key: 'Period', label: 'Period' },
      { key: 'Generated By', label: 'Generated By' },
      { key: 'Date', label: 'Date' },
    ]);
    setExportColumns([
      { key: 'Report', label: 'Report' },
      { key: 'Period', label: 'Period' },
      { key: 'Generated By', label: 'Generated By' },
      { key: 'Date', label: 'Date' },
    ]);
    setResultRows([row]);
  }, [period, profile?.fullName]);

  const runReport = async (reportId: string, reportName: string) => {
    setRunning(reportId);
    try {
      if (reportId === 'daily_cash') await runDailyCash();
      else if (reportId === 'weekly_sales') await runWeeklySales();
      else if (reportId === 'monthly_pl') await runMonthlyPL();
      else if (reportId === 'payroll') await runPayroll();
      else if (reportId === 'credit') await runCredit();
      else if (reportId === 'outstanding_inv') await runOutstandingInvoices();
      else if (reportId === 'payment_methods') await runPaymentMethods();
      else if (reportId === 'expense') await runExpense();
      else runMockPlaceholder(reportName);
      await logHistory(reportName);
      setResultReport(reportName);
    } catch (e: any) {
      Alert.alert('Report Failed', e.message || 'Could not generate this report.');
    } finally {
      setRunning(null);
    }
  };

  return (
    <Screen>
      <View style={{ gap: t.spacing.xl }}>
        <SearchablePicker label="Period" value={period} onChange={setPeriod} options={PERIODS.map((p) => ({ value: p, label: p }))} />

        <View style={{ gap: t.spacing.md }}>
          {REPORTS.map((r) => {
            const Icon = r.icon;
            return (
              <Card key={r.id}>
                <View style={{ flexDirection: 'row', alignItems: 'center', gap: t.spacing.md }}>
                  <View style={{ width: 40, height: 40, borderRadius: 20, backgroundColor: `${r.color}20`, alignItems: 'center', justifyContent: 'center' }}>
                    <Icon size={18} color={r.color} />
                  </View>
                  <View style={{ flex: 1 }}>
                    <Text style={{ fontFamily: t.font.bold, fontSize: t.type.body14.size, color: t.colors.textPrimary }}>{r.name}</Text>
                    <Text style={{ fontFamily: t.font.regular, fontSize: t.type.meta10.size, color: t.colors.textMuted }}>{r.description}</Text>
                  </View>
                  <Button label="Run" size="sm" onPress={() => runReport(r.id, r.name)} loading={running === r.id} disabled={!!running} />
                </View>
              </Card>
            );
          })}
        </View>
      </View>

      <Sheet
        open={!!resultReport}
        onClose={() => setResultReport(null)}
        title={resultReport || undefined}
        subtitle={period}
        side="bottom"
        maxHeight={640}
        footer={<Button label="Export" icon={<Download size={14} color="#fff" />} onPress={() => setExportOpen(true)} fullWidth />}
      >
        <SheetSection label="Results">
          <DataList columns={resultColumns} data={resultRows} rowKey={(r) => String(r.id ?? r.metric ?? r.payment_method ?? r.Report ?? '')} emptyTitle="No data for this period" />
        </SheetSection>
      </Sheet>

      <ExportSheet
        open={exportOpen}
        onClose={() => setExportOpen(false)}
        title={resultReport ? `${resultReport} — ${period}` : 'Report'}
        data={resultRows}
        columns={exportColumns}
        formats={['csv', 'pdf']}
        letterhead="legacy"
      />
    </Screen>
  );
}
